<p>In this bite you learn to catch/raise exceptions.</p><p>Write a simple division function meeting the following requirements:</p><ol><li>when denominator is 0 catch the corresponding exception and return 0.</li><li>when numerator or denominator are not of the right type reraise the corresponding exception.</li><li>if the result of the division (after surviving the exceptions) is negative, raise a <code>ValueError</code></li></ol><p>As always see the tests written in <code>pytest</code> to see what your code need to pass. Have fun!</p>